# Site settings
title: Jenna Blair London
email: jennablairlondon@gmail.com
author: Jenna London
copyright_name: jblair87
description:  #Front-End Development / User Experience / Responsive Design

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  jblair87
learn_profile: jblair87
email_username: : jennablairlondon@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path:     "/posts/page:num/"
plugins: [jekyll-paginate, jekyll-feed]
