# Site settings
title: Jenna Blair Mandel
email: jenna.b.mandel@gmail.com
author: Jenna Mandel
copyright_name: jblair87
description: Front-End Development / User Experience / Responsive Design

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  jblair87
learn_profile: jblair87
email_username: jenna.b.mandel@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path:     "/posts/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
